### ISSUE TITLE
Add conda forge release

### ISSUE THREAD

**Issue by leoank** [broadinstitute/cpg#30]

**Comment by jeskowagner** [comment]
If the use of `cpgdata` and `cpgparser` is intended for Cytodata/SBI2 2024, this issue deserves some renewed interest. Making recipes is fairly quick using `grayskull` as explained [here](https://conda-forge.org/docs/maintainer/adding_pkgs/#creating-recipes).

The result looks as follows. Note that it's missing information on license, because I believe the license is not bundled in the Pypi release. I have also not yet added a maintainer name.

<details>
<summary>cpgparser</summary>

```
{% set name = "cpgparser" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cpgparser-{{ version }}.tar.gz
  sha256: e64deef3bde428a1723f6aa9b3506eabe4a622e53404f51f6b6dfe15a028a261

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - maturin >=1.4,<2.0
    - pip
  run:
    - python >=3.8

test:
  imports:
    - cpgparser
  commands:
    - pip check
  requires:
    - pip

about:
  license: ''
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - PLEASE_ADD_RECIPE_MAINTAINER
```
</details>

<details>
<summary>cpgdata</summary>

```
{% set name = "cpgdata" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cpgdata-{{ version }}.tar.gz
  sha256: 9c20f38e71170f41ece257d2f4d3fd0db1b4972f3863c3432026efa6e303d5c5

build:
  entry_points:
    - cpg = cpgdata.cli.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - click >=8.1.0,<9.0.0
    - pydantic >=2.4.0,<3.0.0
    - polars >=0.19.0,<0.20.0
    - pyarrow >=13.0.0,<14.0.0
    - joblib >=1.3.2,<2.0.0
    - cpgparser >=0.2.0,<0.3.0
    - tqdm >=4.66.0,<5.0.0
    - lark >=1.1.9,<2.0.0

test:
  imports:
    - cpgdata
  commands:
    - pip check
    - cpg --help
  requires:
    - pip

about:
  summary: Cell painting gallery data handling and validation
  license: ''
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - PLEASE_ADD_RECIPE_MAINTAINER
```
</details>
